In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import mannwhitneyu, shapiro, kstest, norm, ttest_ind, t
import math
import numpy as np

In [2]:
df = pd.read_csv('./data/grocerywebsiteabtestdata.csv')

df

        RecordID    IP Address  LoggedInFlag  ServerID  VisitPageFlag
0              1   39.13.114.2             1         2              0
1              2     13.3.25.8             1         1              0
2              3   247.8.211.8             1         1              0
3              4   124.8.220.3             0         3              0
4              5   60.10.192.7             0         2              0
...          ...           ...           ...       ...            ...
184583    184584   114.8.104.1             0         1              0
184584    184585   207.2.110.5             0         2              1
184585    184586   170.13.31.9             0         2              0
184586    184587   195.14.92.3             0         3              0
184587    184588  172.12.115.8             0         2              1

[184588 rows x 5 columns]

In [3]:
df.groupby('ServerID')['VisitPageFlag'].mean()

ServerID
1    0.067640
2    0.053300
3    0.053596
Name: VisitPageFlag, dtype: float64

In [11]:
df.groupby('ServerID')['ServerID'].value_counts()

ServerID
1    61591
2    61463
3    61534
Name: count, dtype: int64

In [25]:
import random

b_group = df.loc[df['ServerID'].isin([2, 3])]
b_group.reset_index(drop=True, inplace=True)
b_group_norm = np.array([]).reshape(0, b_group.shape[1])

for i in range(62000):
    new_el = random.randint(0, len(b_group) - 1)
    b_group_norm = np.vstack([b_group_norm, b_group.iloc[new_el].values])

KeyboardInterrupt:

In [27]:
pd.DataFrame(b_group_norm, columns=b_group.columns)

      RecordID    IP Address LoggedInFlag ServerID VisitPageFlag
0        41972     11.3.67.8            1        2             0
1        46009      45.3.4.9            0        2             1
2        18035   70.11.185.7            1        3             0
3       177490    55.10.21.3            0        2             0
4       103361   41.12.150.1            1        2             0
...        ...           ...          ...      ...           ...
19859    77735     1.9.235.9            1        2             0
19860    70147    76.14.94.4            0        3             0
19861    41413  213.16.121.8            0        3             0
19862    61648   169.10.45.4            1        3             0
19863   160597    56.14.60.9            0        2             0

[19864 rows x 5 columns]

In [7]:
a = df.loc[(df['ServerID'] == 2)]
b = df.loc[df['ServerID'] == 1]

In [11]:
len(b)/(len(a)+len(b))

0.5005200968680417

In [26]:
shapiro(a['VisitPageFlag'])

c:\Users\raven\Projects\tutor\venv\Lib\site-packages\scipy\stats\_axis_nan_policy.py:592: UserWarning: scipy.stats.shapiro: For N > 5000, computed p-value may not be accurate. Current N is 122997.
  res = hypotest_fun_out(*samples, **kwds)

ShapiroResult(statistic=0.23376707303734945, pvalue=5.543640183392948e-181)

In [27]:
shapiro(b['VisitPageFlag'])

c:\Users\raven\Projects\tutor\venv\Lib\site-packages\scipy\stats\_axis_nan_policy.py:592: UserWarning: scipy.stats.shapiro: For N > 5000, computed p-value may not be accurate. Current N is 61591.
  res = hypotest_fun_out(*samples, **kwds)

ShapiroResult(statistic=0.2711322300811546, pvalue=1.2526501551590054e-159)

In [24]:
kstest(a['VisitPageFlag'], norm.cdf)

KstestResult(statistic=0.5, pvalue=0.0, statistic_location=0.0, statistic_sign=-1)

In [25]:
kstest(b['VisitPageFlag'], norm.cdf)

KstestResult(statistic=0.5, pvalue=0.0, statistic_location=0.0, statistic_sign=-1)

In [29]:
mannwhitneyu(a['VisitPageFlag'], b['VisitPageFlag'])

MannwhitneyuResult(statistic=3734000979.5, pvalue=1.1426411024538882e-34)

In [32]:
ttest_ind(a['VisitPageFlag'], b['VisitPageFlag'])

TtestResult(statistic=-12.28620604457121, pvalue=1.1084122256873473e-34, df=184586.0)

In [12]:
t_crit_a = t.ppf(1-(0.95/2), df=len(a)-1)
t_crit_b = t.ppf(1-(0.95/2), df=len(b)-1)

s_a = a['VisitPageFlag'].std()
s_b = b['VisitPageFlag'].std()

mean_a = a['VisitPageFlag'].mean()
mean_b = b['VisitPageFlag'].mean()

left_a = mean_a-t_crit_a*(s_a/math.sqrt(len(a)))
right_a = mean_a+t_crit_a*(s_a/math.sqrt(len(a)))

left_b = mean_b-t_crit_b*(s_b/math.sqrt(len(b)))
right_b = mean_b+t_crit_b*(s_b/math.sqrt(len(b)))

interval_a = [left_a, right_a]
interval_b = [left_b, right_b]

print(interval_a)
print(interval_b)

[np.float64(0.0532435418081589), np.float64(0.053357177323676515)]
[np.float64(0.06757629928757501), np.float64(0.06770320583492666)]

In [15]:
left_b-left_a

np.float64(0.014332757479416113)

In [43]:
((mean_b-mean_a)/mean_a)*100

26.551363641256

In [ ]:
country = [np.random.randint(0, 5) for _ in range(len(df))]
device = [np.random.randint(0, 3) for _ in range(len(df))]

[0,
 1,
 4,
 2,
 3,
 1,
 1,
 1,
 4,
 4,
 4,
 0,
 4,
 4,
 0,
 4,
 4,
 3,
 1,
 4,
 1,
 1,
 4,
 2,
 1,
 4,
 1,
 2,
 4,
 1,
 0,
 2,
 0,
 0,
 3,
 2,
 0,
 0,
 4,
 4,
 0,
 4,
 3,
 0,
 0,
 2,
 3,
 3,
 2,
 0,
 1,
 1,
 1,
 4,
 3,
 4,
 1,
 4,
 1,
 1,
 2,
 3,
 3,
 4,
 4,
 0,
 0,
 1,
 1,
 0,
 1,
 3,
 1,
 1,
 4,
 1,
 4,
 3,
 3,
 1,
 4,
 3,
 0,
 3,
 1,
 3,
 3,
 2,
 1,
 2,
 0,
 3,
 3,
 4,
 0,
 2,
 1,
 0,
 4,
 3,
 0,
 4,
 1,
 2,
 0,
 1,
 4,
 2,
 1,
 0,
 1,
 4,
 1,
 4,
 2,
 0,
 3,
 3,
 0,
 2,
 4,
 0,
 1,
 3,
 4,
 3,
 1,
 0,
 0,
 3,
 2,
 4,
 4,
 3,
 0,
 4,
 0,
 2,
 0,
 0,
 4,
 3,
 2,
 3,
 0,
 4,
 0,
 2,
 3,
 3,
 1,
 0,
 4,
 1,
 0,
 4,
 0,
 0,
 3,
 0,
 4,
 1,
 4,
 3,
 1,
 0,
 3,
 2,
 4,
 3,
 3,
 1,
 1,
 1,
 0,
 4,
 2,
 2,
 3,
 2,
 3,
 0,
 2,
 1,
 1,
 0,
 2,
 0,
 1,
 3,
 4,
 4,
 0,
 3,
 3,
 3,
 3,
 1,
 3,
 0,
 3,
 3,
 3,
 2,
 4,
 4,
 2,
 1,
 2,
 3,
 1,
 4,
 3,
 1,
 1,
 1,
 3,
 4,
 0,
 2,
 3,
 0,
 4,
 3,
 1,
 4,
 0,
 2,
 4,
 0,
 4,
 2,
 3,
 4,
 1,
 2,
 0,
 0,
 4,
 2,
 4,
 1,
 4,
 4,
 1,
 3,
 0,
 4,
 4,
 2,
 1,
 3,
 0,
 4,
 2,
 4,
 2,
 2,
 1,
 1,
 3,
 4,
 4,
 3,
 4,
 4,
 1,
 2,
 2,
 2,
 0,
 4,
 4,
 3,
 0,
 1,
 1,
 0,
 0,
 1,
 2,
 3,
 1,
 4,
 0,
 0,
 4,
 1,
 4,
 4,
 3,
 4,
 3,
 4,
 3,
 0,
 2,
 3,
 4,
 2,
 1,
 2,
 4,
 1,
 2,
 4,
 4,
 1,
 2,
 2,
 4,
 2,
 2,
 0,
 0,
 0,
 2,
 0,
 1,
 3,
 2,
 1,
 4,
 3,
 2,
 3,
 4,
 0,
 4,
 0,
 4,
 3,
 0,
 0,
 4,
 0,
 0,
 0,
 2,
 2,
 3,
 2,
 3,
 4,
 2,
 3,
 3,
 4,
 1,
 1,
 3,
 2,
 2,
 4,
 3,
 1,
 4,
 1,
 3,
 2,
 4,
 4,
 2,
 4,
 4,
 4,
 0,
 2,
 0,
 1,
 1,
 0,
 1,
 1,
 3,
 3,
 0,
 2,
 1,
 1,
 0,
 3,
 1,
 0,
 0,
 3,
 3,
 2,
 3,
 1,
 4,
 3,
 0,
 3,
 1,
 4,
 4,
 4,
 1,
 0,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 4,
 4,
 2,
 1,
 1,
 0,
 2,
 1,
 4,
 0,
 4,
 4,
 1,
 4,
 3,
 0,
 0,
 0,
 4,
 1,
 0,
 1,
 3,
 4,
 4,
 1,
 3,
 2,
 3,
 4,
 4,
 0,
 4,
 1,
 1,
 4,
 0,
 0,
 2,
 1,
 1,
 4,
 0,
 3,
 2,
 3,
 1,
 1,
 4,
 3,
 1,
 4,
 4,
 4,
 1,
 1,
 0,
 4,
 4,
 3,
 3,
 0,
 1,
 4,
 2,
 4,
 0,
 0,
 0,
 4,
 1,
 2,
 2,
 3,
 0,
 3,
 0,
 4,
 4,
 2,
 1,
 2,
 2,
 3,
 1,
 4,
 3,
 1,
 0,
 0,
 4,
 0,
 0,
 2,
 2,
 3,
 4,
 0,
 3,
 3,
 1,
 4,
 2,
 2,
 2,
 1,
 0,
 1,
 1,
 4,
 4,
 4,
 2,
 3,
 1,
 2,
 2,
 3,
 2,
 3,
 3,
 1,
 0,
 1,
 4,
 3,
 4,
 0,
 2,
 0,
 1,
 1,
 4,
 0,
 3,
 2,
 0,
 4,
 3,
 3,
 4,
 0,
 2,
 4,
 1,
 3,
 1,
 2,
 0,
 0,
 2,
 1,
 2,
 3,
 0,
 1,
 3,
 2,
 0,
 2,
 2,
 3,
 2,
 3,
 0,
 4,
 1,
 3,
 3,
 4,
 3,
 3,
 0,
 2,
 0,
 3,
 1,
 1,
 4,
 0,
 0,
 2,
 2,
 1,
 1,
 2,
 1,
 3,
 2,
 1,
 2,
 1,
 1,
 3,
 1,
 2,
 4,
 1,
 0,
 0,
 3,
 2,
 1,
 1,
 3,
 4,
 4,
 2,
 4,
 1,
 0,
 1,
 0,
 4,
 4,
 1,
 4,
 0,
 4,
 4,
 4,
 0,
 0,
 4,
 3,
 4,
 1,
 4,
 3,
 2,
 0,
 2,
 1,
 4,
 2,
 3,
 1,
 3,
 0,
 3,
 2,
 3,
 1,
 0,
 4,
 2,
 4,
 1,
 2,
 2,
 4,
 1,
 2,
 4,
 4,
 2,
 3,
 3,
 1,
 2,
 2,
 3,
 2,
 4,
 3,
 3,
 2,
 4,
 3,
 1,
 1,
 0,
 4,
 4,
 2,
 1,
 2,
 4,
 4,
 0,
 1,
 3,
 0,
 2,
 3,
 4,
 4,
 4,
 3,
 0,
 1,
 0,
 0,
 1,
 4,
 2,
 0,
 3,
 4,
 4,
 4,
 0,
 3,
 4,
 2,
 2,
 0,
 3,
 1,
 2,
 4,
 2,
 4,
 1,
 2,
 4,
 1,
 3,
 0,
 1,
 2,
 0,
 0,
 3,
 2,
 2,
 4,
 2,
 0,
 1,
 0,
 0,
 3,
 4,
 4,
 1,
 1,
 2,
 0,
 4,
 4,
 3,
 0,
 0,
 0,
 2,
 1,
 0,
 4,
 0,
 3,
 0,
 1,
 4,
 0,
 1,
 3,
 2,
 0,
 2,
 3,
 0,
 4,
 4,
 4,
 3,
 4,
 4,
 4,
 0,
 3,
 2,
 3,
 4,
 2,
 3,
 2,
 0,
 0,
 0,
 1,
 0,
 1,
 3,
 2,
 0,
 1,
 2,
 2,
 0,
 1,
 1,
 0,
 1,
 3,
 4,
 3,
 3,
 4,
 4,
 0,
 3,
 4,
 2,
 4,
 4,
 2,
 4,
 4,
 2,
 0,
 0,
 3,
 2,
 0,
 1,
 2,
 0,
 1,
 3,
 0,
 1,
 2,
 1,
 0,
 1,
 2,
 4,
 2,
 0,
 1,
 4,
 1,
 0,
 1,
 0,
 4,
 3,
 2,
 1,
 1,
 0,
 3,
 2,
 4,
 1,
 1,
 0,
 2,
 0,
 4,
 3,
 3,
 1,
 3,
 0,
 3,
 3,
 2,
 3,
 4,
 0,
 1,
 1,
 2,
 0,
 4,
 1,
 2,
 1,
 0,
 4,
 3,
 3,
 4,
 3,
 2,
 1,
 1,
 2,
 0,
 1,
 0,
 4,
 4,
 0,
 0,
 2,
 2,
 3,
 1,
 0,
 2,
 3,
 4,
 2,
 1,
 0,
 2,
 3,
 0,
 2,
 3,
 2,
 1,
 4,
 4,
 0,
 0,
 0,
 2,
 2,
 3,
 1,
 4,
 3,
 3,
 3,
 3,
 0,
 4,
 2,
 4,
 2,
 3,
 4,
 2,
 4,
 1,
 0,
 3,
 2,
 0,
 2,
 3,
 4,
 2,
 0,
 3,
 2,
 0,
 2,
 1,
 2,
 3,
 0,
 1,
 3,
 4,
 1,
 3,
 2,
 4,
 2,
 1,
 3,
 2,
 3,
 2,
 0,
 3,
 0,
 1,
 1,
 0,
 0,
 1,
 2,
 3,
 1,
 3,
 2,
 4,
 0,
 2,
 1,
 3,
 2,
 0,
 1,
 3,
 1,
 2,
 2,
 3,
 4,
 2,
 0,
 2,
 4,
 2,
 2,
 ...]

In [51]:
df['Country'] = country
df['Device'] = device

In [53]:
df['Country'] = df['Country'].map({
    0: 'Russia',
    1: 'England',
    2: 'Germany',
    3: 'Finland',
    4: 'Belarus'
})

df['Device'] = df['Device'].map({
    0: 'Android',
    1: 'iOS',
    2: 'Windows'
})

In [55]:
df.to_csv('./data/data_with_geo_device.csv')